name: Program Integration Tests

on:
  push:
    branches: [main]
    paths:
      - 'program/**'
      - 'Cargo.*'
      - 'Makefile'
      - 'tests/integration/**'
      - '.github/workflows/program-integration.yml'
      - 'clients/rust/**'
      - 'scripts/generate-client.js'
  pull_request:
    branches: [main]
    paths:
      - 'program/**'
      - 'Cargo.*'
      - 'Makefile'
      - 'tests/integration/**'
      - '.github/workflows/program-integration.yml'
      - 'clients/rust/**'
      - 'scripts/generate-client.js'
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

permissions:
  contents: read

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Shank
        run: cargo install shank-cli

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            .
            tests/integration-tests

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 'lts/*'
            registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10.12.3
            run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
            path: ${{ env.STORE_PATH }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-pnpm-store-
    
      - name: Install dependencies
        run: |
          make install

      - name: Setup Solana CLI
        uses: ./.github/actions/setup-solana

      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          make test-integration

      - name: Show failure logs
        if: failure()
        uses: ./.github/actions/show-failure-logs
        with:
            test-type: "Program integration"