repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.(json)$'
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust code
        entry: cargo fmt --all --check
        language: system
        files: '\.rs$'
        pass_filenames: false

  - repo: local
    hooks:
      - id: shank-idl-check
        name: Check IDL is up to date
        entry: bash -c 'npm run generate-idl > /dev/null 2>&1 && git diff --exit-code idl'
        language: system
        files: '^program/src/.*\.rs$'
        pass_filenames: false
      - id: client-generation-check
        name: Check clients are up to date
        entry: bash -c 'npm run generate-clients && git diff --exit-code clients'
        language: system
        files: '^(program/src/.*\.rs|idl/.*\.json)$'
        pass_filenames: false
